import json
from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from datetime import datetime

def add_heading(doc, text, level=1, color=None):
    p = doc.add_heading(text, level=level)
    if color:
        for run in p.runs:
            run.font.color.rgb = RGBColor(*color)
    return p

def add_table_row(table, label, value, shade=False):
    row = table.add_row()
    row.cells[0].text = label
    row.cells[1].text = str(value)
    row.cells[0].paragraphs[0].runs[0].bold = True

def generate_cam(score_file="last_score.json"):
    with open(score_file) as f:
        data = json.load(f)

    company = data["company"]
    final_score = data["final_score"]
    decision = data["decision"]
    rate = data.get("rate", "N/A")
    scores = data["scores"]
    red_flags = data["red_flags"]
    officer_notes = data.get("officer_notes", "")

    doc = Document()

    # Title
    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title.add_run("CREDIT APPRAISAL MEMORANDUM (CAM)")
    run.bold = True
    run.font.size = Pt(18)
    run.font.color.rgb = RGBColor(0, 51, 102)

    doc.add_paragraph()

    # Header table
    table = doc.add_table(rows=0, cols=2)
    table.style = "Table Grid"
    add_table_row(table, "Company Name", company)
    add_table_row(table, "Date of Appraisal", datetime.now().strftime("%d %B %Y"))
    add_table_row(table, "Prepared By", "Intelli-Credit AI Engine")
    add_table_row(table, "Credit Score", str(final_score) + " / 100")
    add_table_row(table, "Recommendation", decision)
    if rate != "N/A":
        add_table_row(table, "Suggested Interest Rate", rate)

    doc.add_paragraph()

    # Decision box
    decision_colors = {"APPROVE": (0,128,0), "APPROVE WITH CONDITIONS": (255,140,0), "REFER TO CREDIT COMMITTEE": (0,0,255), "REJECT": (255,0,0)}
    color = decision_colors.get(decision, (0,0,0))
    p = doc.add_paragraph()
    run = p.add_run("FINAL DECISION: " + decision)
    run.bold = True
    run.font.size = Pt(14)
    run.font.color.rgb = RGBColor(*color)
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph()

    # Five Cs
    add_heading(doc, "1. FIVE Cs CREDIT ANALYSIS", level=1)

    for c_name, s in scores.items():
        add_heading(doc, c_name + " — " + str(s["score"]) + "/100 (" + s["rating"] + ")", level=2)
        doc.add_paragraph(s["reasoning"])
        if s.get("key_findings"):
            doc.add_paragraph("Key Findings:", style="Normal").runs[0].bold = True
            for f in s["key_findings"]:
                doc.add_paragraph(f, style="List Bullet")
        if s.get("red_flags"):
            p = doc.add_paragraph()
            run = p.add_run("RED FLAGS:")
            run.bold = True
            run.font.color.rgb = RGBColor(255,0,0)
            for f in s["red_flags"]:
                p2 = doc.add_paragraph(f, style="List Bullet")
                p2.runs[0].font.color.rgb = RGBColor(255,0,0)

    # Red flags summary
    if red_flags:
        add_heading(doc, "2. RED FLAG SUMMARY", level=1)
        for i, f in enumerate(red_flags, 1):
            p = doc.add_paragraph(str(i) + ". " + f, style="List Number")
            p.runs[0].font.color.rgb = RGBColor(200,0,0)

    # Officer notes
    if officer_notes:
        add_heading(doc, "3. CREDIT OFFICER OBSERVATIONS", level=1)
        doc.add_paragraph(officer_notes)

    # Recommendation
    add_heading(doc, "4. RECOMMENDATION", level=1)
    rec_text = {
        "APPROVE": "Based on comprehensive analysis, the credit committee may APPROVE this facility subject to standard documentation and security creation.",
        "APPROVE WITH CONDITIONS": "The facility may be APPROVED WITH CONDITIONS. Enhanced monitoring, additional collateral, and quarterly review recommended.",
        "REFER TO CREDIT COMMITTEE": "Given the mixed risk profile, this case must be REFERRED TO THE CREDIT COMMITTEE for detailed deliberation.",
        "REJECT": "Based on the analysis, it is recommended to REJECT this credit proposal due to high risk indicators identified across multiple parameters."
    }
    doc.add_paragraph(rec_text.get(decision, ""))

    # Disclaimer
    doc.add_paragraph()
    p = doc.add_paragraph("Disclaimer: This CAM was generated by Intelli-Credit AI and must be reviewed and approved by an authorized credit officer before any lending decision.")
    p.runs[0].font.size = Pt(8)
    p.runs[0].font.color.rgb = RGBColor(128,128,128)

    filename = company.replace(" ", "_") + "_CAM_" + datetime.now().strftime("%Y%m%d") + ".docx"
    doc.save(filename)
    print("CAM report saved: " + filename)
    return filename

if __name__ == "__main__":
    generate_cam()
